/**
 * Global API Configuration
 * This file is served by backend and auto-updates based on .env
 * 
 * Usage: Add this to your HTML files BEFORE any API calls
 * <script src="/config.js"></script>
 */

// This file is dynamically generated by backend/server.js
// It reads API_BASE_URL from backend/.env
// 
// To change API URL:
// 1. Edit backend/.env
// 2. Change API_BASE_URL=your-url
// 3. Restart backend server
// 4. All frontend files will automatically use new URL

// Fallback if backend is not running
if (typeof window !== 'undefined' && !window.API_BASE_URL) {
  const hostname = window.location.hostname;
  const port = window.location.port;
  
  if (hostname === 'localhost' || hostname === '127.0.0.1') {
    window.API_BASE_URL = `http://${hostname}:${port || 3000}`;
  } else {
    window.API_BASE_URL = 'https://api.anocab.com';
  }
  
  console.warn('⚠️ Using fallback API URL:', window.API_BASE_URL);
  console.warn('💡 Make sure backend server is running');
}

// Also define as const for backward compatibility
const API_BASE_URL = window.API_BASE_URL;
